; M5Stack PaperMono
[env:m5stack-papermono]
extends = esp32s3_base
board_level = release
board = esp32-s3-devkitm-1
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L
upload_protocol = esptool

custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = M5STACK_PAPERMONO
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_display_name = M5Stack PaperMono
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_partition_scheme = 16MB
custom_meshtastic_has_mui = false
custom_meshtastic_has_ink_hud = false

build_flags =
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -D M5STACK_PAPERMONO
  -D USE_EINK
  -D USE_EINK_LGFX
  -D ESP32S3
  -D BOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -I variants/esp32s3/m5stack_papermono
  -DARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
  ${esp32s3_base.build_src_filter}
  +<../variants/esp32s3/m5stack_papermono>
  -<graphics/EInkDisplay2.cpp>
  -<graphics/EInkDynamicDisplay.cpp>

lib_deps =
  ${esp32s3_base.lib_deps}
  # renovate: datasource=custom.pio depName=LovyanGFX packageName=lovyan03/library/LovyanGFX
  lovyan03/LovyanGFX@1.2.28
  # renovate: datasource=custom.pio depName=M5IOE1 packageName=m5stack/library/M5IOE1
  m5stack/M5IOE1
  # renovate: datasource=custom.pio depName=M5PM1 packageName=m5stack/library/M5PM1
  m5stack/M5PM1
  # renovate: datasource=custom.pio depName=ArtronShop_RX8130CE packageName=artronshop/library/ArtronShop_RX8130CE
  artronshop/ArtronShop_RX8130CE@1.0.0